"""Update verify column

Revision ID: bf747ad5270d
Revises: d25ec9b247a5
Create Date: 2023-08-26 14:41:37.483826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf747ad5270d'
down_revision: Union[str, None] = 'd25ec9b247a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verify', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verify', 'is_active')
    # ### end Alembic commands ###
